version: "3.8"

services:

  app:
    build:
      context: .
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    environment:
      - ENGINE="django.db.backends.postgresql:${DB_ENGINE}"
      - DB_NAME="starlink.db:${DB_NAME}"
      - DB_USER="postgres:${DB_USER}"
      - DB_PASSWORD="postgres:${DB_PASSWORD}"
      - DB_HOST="postgres:${DB_HOST}"
      - DB_PORT="5432:${DB_PORT}"
    depends_on:
      - postgres
    restart: always

  postgres:
    image: postgres:9.6
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    volumes:
      - ./postgres:/var/lib/postgresql/data
    restart: always
